### PR TITLE
Add France data ingest

### PR DESCRIPTION
**Pull request by haroldm**
This PR allows to run this model (with rtlive-model notebook) against French data.
Are you interested in merging that to master and what improvements do you need ?

### CODE REVIEW

**Comment by AlexAndorra** [comment]
Looks nice, thanks! If not merged into this repo, could be interesting to set it up in another repo, like was done for German data? Would be happy to collaborate on that 😉

**Comment by haroldm** [comment]
I'll wait a little more for a maintainer input on this PR: I don't feel merging would induce much overhead for them (especially as French data does not seem to need correction).

Either way it would be nice to compute and provide a visualization for France data but this is out of scope of covid-model.

**Comment by k-sys** [comment]
Hello thank you for this – we aren't accepting additional country support at this time. We've frozen the code for stability. Feel free to fork and self-publish the results.

**Comment by gkossakowski** [comment]
@haroldm @AlexAndorra: I've been running a fork of rt.live for Europe at rteu.live, using previous generation of the model and custom frontend. Would you be interested in collaborating? I'd especially love to have regional estimates R_t for countries in Europe as countries move to regional responses.

**Comment by sqbl** [comment]
> @haroldm @AlexAndorra: I've been running a fork of rt.live for Europe at rteu.live, using previous generation of the model and custom frontend. Would you be interested in collaborating? I'd especially love to have regional estimates R_t for countries in Europe as countries move to regional responses.

@gkossakowski, I have a model of daily danish data, I'll happily share it.

**Comment by AlexAndorra** [comment]
Thanks for reaching out @gkossakowski. Depending on what your need is, I'd be down for this! I won't be a big help on the front-end side, but I can clearly help on the stats and model side, as I'm involved in the PyMC project -- adaptations will probably be needed. 
Just glanced at the website and the UI is really nice!
Just had two quick questions:
- Any reasons you're not using the last version of the model, IIUC?
- At least for France, I'd aim to model at the department-level, not at the regional one

**Comment by gkossakowski** [comment]
A quick reply as I'm dealing with life logistics in San Francisco. We got stuck on the previous model for two reasons:
1. ECDC doesn't publish the number of tests executed each day so we can't compute positive rate easily across countries in the EU
2. Simply didn't get around to digging into v2 that seems to require more heavy infra than a single box to run (I might be wrong about that)

**Comment by AlexAndorra** [comment]
Thanks for the context. So it sounds to me like I could see how to transition to the latest model -- tell me if I'm wrong.
I'll be happy to fork the repo and look into that when I have time 😉 Thanks for this initiative, very useful!

**Comment by gkossakowski** [comment]
Yes! checking if we could transist to the latest model would be great.

@haroldm, @AlexAndorra and @sqbl, maybe we can hop onto https://github.com/gkossakowski/covid-19/issues/3 to continue the discussion there and spare notification traffic for k-sys?

**Comment by gkossakowski** [comment]
oh and I totally forgot to say that the credit for the frontend for rteu.live goes to @lynnagara

**Comment by haroldm** [comment]
Computed data is now available at https://r0france.live/. I try to update it regularly.
Anyone who want to contribute (front-end dev, compute power) is welcome.

**Comment by michaelosthege** [comment]
> Computed data is now available at https://r0france.live/. I try to update it regularly.
> Anyone who want to contribute (front-end dev, compute power) is welcome.

Hi @haroldm , congrats!
Make sure to check out https://github.com/rtcovidlive/rtlive-global, https://github.com/michaelosthege/rtlive-dash-de and https://rtlive.de/global

**Pull request closed without merging**
