### PR TITLE
Add generative model tutorial. 

### PR DESCRIPTION
**Pull request by twiecki**
Also creates a docs subdir and moves `rtlive-model.ipynb` into it.

### CODE REVIEW

**Comment by michaelosthege** [comment]
@twiecki in #20 we create a `notebooks` subdir, but I think we should have just one. What do you think is more appropriate?

**Comment by twiecki** [comment]
Probably if I were to look for stand-alone docs in a repo the notebooks dir would be the first place.

**Comment by michaelosthege** [comment]
A few smaller suggestions:

1. `get_and_process_covidtracking_data` can be replaced with `get_data` from #19:
```
covid.data.get_data(country='us', run_date=pd.Timestamp.today())
```

2. data-download (1.) can be moved far down to after the synthetic example
3. you can add a visualization of the model:
```
pmodel = model.build()
pm.model_to_graphviz()
```
4. `ax.legend(frameon=False)` looks nicer for cell 27
5. formatting problem in the line `we will model it with a probability distribution from this study30119-3/pdf) `

**Comment by k-sys** [comment]
Will merge now and fix @michaelosthege 's suggestions.

**Pull request merged**
